# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
version: '3'
env:
  REPO: ghcr.io/nuvolaris
  NAME: openwhisk-standalone
  TAG: neo-latest
  DOCKER_URL: https://download.docker.com/linux/static/stable/x86_64/docker-18.06.3-ce.tgz
  WSK_URL: https://github.com/apache/openwhisk-cli/releases/download/1.2.0/OpenWhisk_CLI-1.2.0-linux-amd64.tgz

tasks:

  build-and-push:
    deps:
      - build
    cmds:
      - docker push $REPO/$NAME:$TAG

  build:
    deps: 
      - download
      - openwhisk
    cmds:
      - docker build . -t $REPO/$NAME:$TAG

  download:
    cmds:
      - curl -sL $DOCKER_URL | tar xzvf -
      - mkdir -p wsk ; curl -sL $WSK_URL | tar xzvf - -C wsk
    status:
      - test -f wsk/wsk
      - test -d docker

  openwhisk:
    dir: openwhisk
    cmds:
      - ./gradlew -DskipTests :core:standalone:build
    status:
      - test -f bin/openwhisk-standalone.jar

  clean:
    cmds:
      - cd openwhisk && ./gradlew clean
      - rm -Rvf wsk
      - rm -Rvf docker
