# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
version: '3'
vars:
  MILESTONE: neo
  REPO: ghcr.io
  IMAGE: nuvolaris/openwhisk-standalone
  TAG:
    sh: git describe --tags --abbrev=0 2>/dev/null || echo {{.MILESTONE}}-latest
  HOSTNAME:
    sh: hostname -f
  RUNTIMES:
    sh: cat conf/runtimes.json
  STANDALONE: "{{.REPO}}/{{.IMAGE}}:{{.TAG}}"
  APIHOST: http://{{.HOSTNAME}}:8080
  WHISK_SYSTEM: "789c46b1-71f6-4ed5-8c54-816aa4f8c502:abczO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP"
  GUEST: "23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP"

tasks:

  buildx-and-push:
    deps:
     - compile
    cmds:
     - docker buildx build --platform linux/amd64,linux/arm64 -t {{.STANDALONE}} . --push

  build:
    deps: 
      - compile
    cmds:
      - docker build . -t {{.STANDALONE}} 
      
  show-tag: echo {{.TAG}}

  controller:
    dir: openwhisk
    cmds:
      - ./gradlew distTar
      - tar xvf core/controller/build/distributions/controller.tar -C ..
    status:
      - test -d ../controller
  
  admin:
    dir: openwhisk
    deps:
      - controller
    cmds:
      - ./gradlew :tools:admin:build
      - cp bin/wskadmin-next ../controller/bin/
    status:
      - test -f ../controller/bin/wskadmin-next

  compile:
    deps:
      - admin
      - controller

  clean: |
    rm -rvf controller
    cd openwhisk
    ./gradlew clean 
  
  # val conf = new org.apache.openwhisk.core.cli.Conf(Seq("user", "create", "--auth", key, subject))

  setup:
    cmds:
      - wsk property set --apihost http://localhost:3233 --auth '{{.GUEST}}'
      #- controller/bin/wskadmin-next -v -c conf/standalone.conf user create --auth {{.GUEST}} guest
      #- controller/bin/wskadmin-next -v -c conf/standalone.conf user create --auth {{.WHISK_SYSTEM}} whisk-system

  run-full:
    deps:
      - compile
    cmds:
      - bash -x controller/bin/controller 0
    env:
      CONTROLLER_OPTS: >
        -Dconfig.file=conf/standalone.conf
        -Dwhisk-config.whisk.api.host.name={{.HOSTNAME}}
        -Dwhisk-config.runtimes.manifest='{{.RUNTIMES}}'
        -Dwhisk-config.port=8080
        -Dwhisk-config.whisk.api.host.port=8080
        -Dwhisk-config.whisk.api.host.proto=http
        -Dwhisk-config.controller.instances=1
        -Dwhisk-config.limits.actions.invokes.concurrent=30
        -Dwhisk-config.limits.actions.invokes.perMinute=60
        -Dwhisk-config.limits.triggers.fires.perMinute=60
        -Dwhisk-config.limits.actions.sequence.maxLength=50
  

  run-local:
    cmds:
      - >
       docker run -ti
       -p 3232:3232 -p 3233:3233
       -v /var/run/docker.sock:/var/run/docker.sock
       {{.STANDALONE}} {{.CLI_ARGS}}
    interactive: true


  deploy-local: kubectl apply -f nuvolaris/standalone