version: '3'

vars:
  TEST: ""

tasks:
  setup: 
    silent: true

  run-setup:
    cmds:
     - rm -Rvf ../openwhisk-utilities
     - ./tools/github/setup.sh
     - docker ps -qa | xargs docker rm -f
    dir: openwhisk

  run-test:
    silent: true
    cmds:
    - |-
      if test -z "{{.TEST}}" ; 
      then ls tools/github/run* 
      echo use TEST=x of Unit, System etc
      else 
      ./tools/github/run{{.TEST}}Tests.sh
      fi
    env:
      TEST_SUITE: "{{.TEST}}"
    dir: openwhisk

  actions:
    cmds:
     - rm -f actions.tar
     - > 
        tar cvf ../actions.tar 
        .github/workflows tools/github
        tests/src/test/scala/org/apache/openwhisk/core/admin/WskAdminTests.scala
        common/scala/Dockerfile
        ansible/group_vars/all
        tests/dat/actions/unicode.tests/src/dotnet2.2/Apache.OpenWhisk.UnicodeTests.Dotnet/Unicode.cs
    dir: openwhisk


