# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:

  setup-repo:
    - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    - helm repo update

  view-values:
    - helm show values prometheus-community/prometheus

  setup-minimal: 
    - |
      helm install nuvolaris-prometheus prometheus-community/prometheus -f values.yaml

  cleanup-minimal:
    - helm uninstall nuvolaris-prometheus


  deploy:prometheus:
    - kubectl apply -f prometheus

  deploy:alertmanager:
    - kubectl apply -f alertmanager

  deploy:nodexporter:
    - kubectl apply -f nodeexporter

  deploy:kubestate:
    - kubectl apply -f kubestate


  deploy-minimal:
    - kubectl apply -f prometheus
    - kubectl apply -f alertmanager
    - kubectl apply -f kubestate

  clean: 
    - kubectl delete -f alertmanager
    - kubectl delete -f prometheus   
    - kubectl delete -f kubestate
    - kubectl delete -f nodeexporter
