# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
version: '3'


vars:
  NAMESPACE: monitoring
  KUBECTL: "kubectl --namespace {{.NAMESPACE}}"

tasks:
  status:
    cmds:
      - echo "*** Nodes"
      - "{{.KUBECTL}} get nodes"
      - echo "*** Pods"
      - "{{.KUBECTL}} get po"
      - echo "*** Services"
      - "{{.KUBECTL}} get svc"
    silent: true
    ignore_error: true

  prometheus-deploy:
    cmds:
      - kubectl apply --server-side -f deploy/manifests/setup
      - until kubectl get servicemonitors --all-namespaces ; do date; sleep 1; echo ""; done
      - kubectl apply -f deploy/manifests/

  prometheus-undeploy:
    cmds:
      - kubectl delete --ignore-not-found=true -f deploy/manifests/ -f deploy/manifests/setup

  prometheus-gui:
    cmds:
      - kubectl --namespace monitoring port-forward svc/prometheus-k8s 9090

  alertmanager-gui:
    cmds:
      - kubectl --namespace monitoring port-forward svc/alertmanager-main 9093

  grafana-gui:
    cmds:
      - kubectl --namespace monitoring port-forward svc/grafana 3000
