apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3ninja
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: s3ninja
  template:
    metadata:
      labels:
        app.kubernetes.io/name: s3ninja
    spec:
      containers:
      - name: s3ninja 
        image:  scireum/s3-ninja
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 250m
