apiVersion: v1
kind: Service
metadata:
  name: s3ninja-svc
spec:
  type: NodePort
  ports:
    - port: 9444
      targetPort: 9000
      protocol: TCP
      name: http
      nodePort: 30444
  selector:
    app.kubernetes.io/name: s3ninja
