apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: nuvolaris-prometheus
    meta.helm.sh/release-namespace: nuvolaris  
  labels:
    app.kubernetes.io/instance: nuvolaris-prometheus    
    app.kubernetes.io/name: alertmanager
  name: nuvolaris-prometheus-alertmanager
  namespace: nuvolaris
data:
  alertmanager.yml: |
    global: {}
    receivers:
    - name: default-receiver
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: default-receiver
      repeat_interval: 3h
    templates:
    - /etc/alertmanager/*.tmpl

