apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-nuvolaris-prometheus-alertmanager
  namespace: nuvolaris
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: nuvolaris-prometheus
    app.kubernetes.io/name: alertmanager  
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard