apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: nuvolaris-prometheus
    app.kubernetes.io/name: alertmanager
  name: nuvolaris-prometheus-alertmanager
  namespace: nuvolaris