apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: nuvolaris-prometheus
    meta.helm.sh/release-namespace: nuvolaris
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: nuvolaris-prometheus
    app.kubernetes.io/name: prometheus
  name: nuvolaris-prometheus-server
  namespace: nuvolaris
data:
  alerting_rules.yml: |
    {}
  alerts: |
    {}
  allow-snippet-annotations: "false"
  prometheus.yml: |
    global:
      evaluation_interval: 1m
      scrape_interval: 1m
      scrape_timeout: 10s
    rule_files:
    - /etc/config/recording_rules.yml
    - /etc/config/alerting_rules.yml
    - /etc/config/rules
    - /etc/config/alerts
    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9999
    - job_name: ow-controller
      static_configs:
      - targets:
        - controller:3233
    - job_name: kafka
      static_configs:
      - targets:
        - kafka:9071
    - job_name: 'kube-state-metrics'
      static_configs:
      - targets: ['nuvolaris-prometheus-kube-state-metrics.nuvolaris.svc.cluster.local:8080']        
    - job_name: 'kubelet'
      kubernetes_sd_configs:
      - role: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true  # Required with Minikube.
      authorization:
          credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token         
    - job_name: 'cadvisor'
      kubernetes_sd_configs:
      - role: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true  # Required with Minikube.
      authorization:
          credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token         
      metrics_path: /metrics/cadvisor                                                
  recording_rules.yml: |
    {}
  rules: |
    {}
