apiVersion: v1
kind: Service
metadata:
  name: nuvolaris-prometheus-server
  namespace: nuvolaris
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: nuvolaris-prometheus
spec:
  type: NodePort
  ports:
  - name: http
    port: 9999
    protocol: TCP
    targetPort: 9999
    nodePort: 30299  
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: nuvolaris-prometheus
    app.kubernetes.io/name: prometheus
  sessionAffinity: None
