---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper
  namespace: nuvolaris
  labels:
    app: zookeeper
data:
  zoo.cfg: |
    tickTime=2000
    clientPort=2181
    initLimit=5
    syncLimit=2
    dataDir=/data
    dataLogDir=/datalog
    server.0=zookeeper-0.zookeeper:2888:3888
