---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: nuvolaris
  labels:
    app: zookeeper
spec:
  selector:
    name: zookeeper
  clusterIP: None
  ports:
    - port: 2181
      name: "zookeeper"
    - port: 2888
      name: "server"
    - port: 3888
      name: "leader-election"
