apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: nuvolaris-prometheus
    app.kubernetes.io/name: kube-state-metrics
  name: nuvolaris-prometheus-kube-state-metrics
  namespace: nuvolaris
spec:
  type: ClusterIP 
  sessionAffinity: None  
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: nuvolaris-prometheus
    app.kubernetes.io/name: kube-state-metrics