apiVersion: v1
kind: ServiceAccount
metadata:
  name: nuvolaris-prometheus-server
  namespace: nuvolaris
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: nuvolaris-prometheus    
    app.kubernetes.io/name: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nuvolaris-prometheus-server
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: nuvolaris-prometheus
    app.kubernetes.io/name: prometheus
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  - endpoints
  - pods
  - ingresses
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses/status
  - ingresses
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nuvolaris-prometheus-server
subjects:
- kind: ServiceAccount
  name: nuvolaris-prometheus-server
  namespace: nuvolaris