name: openwhisk-standalone
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

        - name: Checkout
          uses: actions/checkout@v2
          with:
            submodules: recursive

        - name: Build
          run: |
             bash cisetup.sh
             task build
         - name: Log in to the Container registry
           uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
           with:
             registry: ghcr.io
             username: ${{ github.actor }}
             password: ${{ secrets.GITHUB_TOKEN }}

         - name: Metadata
           id: meta
           uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
           with:
              images: ghcr.io/nuvolaris/openwhisk-standalone

         - name: Push        
           uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
           with:
             context: .
             push: true
             tags: neo-latest
