apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: nuvolaris-prometheus
    app.kubernetes.io/name: prometheus-node-exporter
  name: nuvolaris-prometheus-prometheus-node-exporter
  namespace: nuvolaris
spec:
  sessionAffinity: None
  type: ClusterIP
  internalTrafficPolicy: Cluster
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app.kubernetes.io/instance: nuvolaris-prometheus
    app.kubernetes.io/name: prometheus-node-exporter
