apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: nuvolaris-prometheus
    app.kubernetes.io/name: prometheus-node-exporter
  name: nuvolaris-prometheus-prometheus-node-exporter
  namespace: nuvolaris